spring.datasource:
  url: jdbc:mysql://localhost/Spring_movie_db?createDatabaseIfNotExist=true&serverTimezone=UTC
  username: root
  password:
  driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080

springdoc:
  api-docs.path: /api-docs

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  jackson:
    mapper:
      accept-case-insensitive-enums: true

spring.jpa.show-sql: true

MovieDatabase:
  genres[0]: comedy
  genres[1]: adventure
  genres[2]: romantic
  genres[3]: action